name: Build Docker Images
on: [push, repository_dispatch]

jobs:
  publish-docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - id: fluidd
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: fluidd-core
          repo: fluidd
          excludes: prerelease, draft

      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker image metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{raw}}
            type=ref,event=pr
            type=sha,format=long
            type=raw,value=latest-develop,enable=${{ github.ref == 'refs/heads/develop' }}
            type=raw,value=latest-master,enable=${{ github.ref == 'refs/heads/master' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUSH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            "PRINTER=localhost"
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: latest, ${{ steps.fluidd.outputs.release }}

